### ISSUE TITLE
Photo album

### ISSUE THREAD

**Issue by adina** [swcarpentry/communications#17]
https://github.com/adina/communications/issues/9

**Comment by weaverbel** [comment]
@adina @gvwilson Not sure what this issue is asking. We have set up an Instagram account for Software Carpentry at https://www.instagram.com/swcarpentry/ I have the log in details and they have been sent to the steering committee. We also have a Facebook account that @k8hertweck is managing where pictures can be displayed.  Happy to share info of how to get images 'out there'.

**Comment by gvwilson** [comment]
I think that all means this one can be closed - thanks.

**Comment by tracykteal** [comment]
Any photos we use or display should have the appropriate photo release. @erinbecker has been putting together a collection that has photo release permissions.
